# Generated by Django 4.1.7 on 2023-03-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_authormodel_github_authormodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('origin', models.URLField(default='')),
                ('source', models.URLField(default=models.URLField(default=''))),
                ('description', models.CharField(default='', max_length=500)),
                ('contentType', models.CharField(default='text/plain', max_length=50)),
                ('content', models.TextField(default='')),
                ('count', models.PositiveIntegerField(default=0)),
                ('comments', models.URLField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(default='PUBLIC', max_length=7)),
                ('unlisted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.authormodel')),
                ('categories', models.ManyToManyField(to='API.categoriesmodel')),
            ],
        ),
    ]
