# Generated by Django 4.1.6 on 2023-02-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_post_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
