# Generated by Django 4.1.6 on 2023-03-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_comment_id_remove_post_id_comment_comment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
    ]
