# Generated by Django 4.1.6 on 2023-03-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_remove_comment_comment_id_remove_post_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default=' ', max_length=100, primary_key=True, serialize=False),
        ),
    ]
